Update CICD.yml

diff --git a/.github/workflows/CICD.yml b/.github/workflows/CICD.yml
--- a/.github/workflows/CICD.yml
+++ b/.github/workflows/CICD.yml
@@ -42,27 +42,28 @@ jobs:
     steps:
       - name: Set target IP
         run: |
-          STATUS=$(curl -o /dev/null -w "%{http_code}" "http://${{ secrets.LIVE_SERVER_IP }}/env")
-          echo $STATUS
-          if [ $STATUS = 200 ]; then
-            CURRENT_UPSTREAM=$(curl -s "http://${{ secrets.LIVE_SERVER_IP }}/env")
-          else
-            CURRENT_UPSTREAM=green
-          fi
-          echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
-          if [ $CURRENT_UPSTREAM = blue ]; then
-            echo "CURRENT_PORT=8080" >> $GITHUB_ENV
-            echo "STOPPED_PORT=8081" >> $GITHUB_ENV
-            echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
-          elif [ $CURRENT_UPSTREAM = green ]; then
-            echo "CURRENT_PORT=8081" >> $GITHUB_ENV
-            echo "STOPPED_PORT=8080" >> $GITHUB_ENV
-            echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
-          else
-            echo "error"
-            exit 1
-          fi
-          
+         STATUS=$(curl -o /dev/null -w "%{http_code}" "http://${{ secrets.LIVE_SERVER_IP }}/env")
+         echo "HTTP STATUS: $STATUS"
+         if [[ "$STATUS" == "200" ]]; then
+           CURRENT_UPSTREAM=$(curl -s "http://${{ secrets.LIVE_SERVER_IP }}/env")
+         else
+           CURRENT_UPSTREAM="green"
+         fi
+         echo "CURRENT_UPSTREAM=$CURRENT_UPSTREAM" >> $GITHUB_ENV
+
+         if [[ "$CURRENT_UPSTREAM" == "blue" ]]; then
+           echo "CURRENT_PORT=8080" >> $GITHUB_ENV
+           echo "STOPPED_PORT=8081" >> $GITHUB_ENV
+           echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
+         elif [[ "$CURRENT_UPSTREAM" == "green" ]]; then
+           echo "CURRENT_PORT=8081" >> $GITHUB_ENV
+           echo "STOPPED_PORT=8080" >> $GITHUB_ENV
+           echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
+         else
+           echo "Error: Unexpected CURRENT_UPSTREAM value"
+           exit 1
+         fi
+        
       - name: Docker compose
         uses: appleboy/ssh-action@master
         with:
